"Resources"
{
	"materials\sprites\obj_icons\icon_obj_1bw_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_neutral_locked.vmt"	"file"
	
	"materials\sprites\obj_icons\icon_obj_2ar_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_neutral_locked.vmt"	"file"
	
	"materials\sprites\obj_icons\icon_obj_3l_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_neutral_locked.vmt"	"file"

	
	"materials\sprites\obj_icons\icon_obj_4sw_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_neutral_locked.vmt"	"file"
	
	"materials\sprites\obj_icons\icon_obj_5f_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_neutral_locked.vmt"	"file"

	"materials\sprites\obj_icons\icon_obj_6ba_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_neutral_locked.vmt"	"file"

	
	"materials\sprites\obj_icons\icon_obj_7bo_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_neutral_locked.vmt"	"file"

	"materials\sprites\obj_icons\icon_obj_8rw_blu.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_blu_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_red.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_red_locked.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_neutral.vmt"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_neutral_locked.vmt"	"file"
	
	"materials\sprites\obj_icons\icon_obj_1bw_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_1bw_neutral_locked.vtf"	"file"
	
	"materials\sprites\obj_icons\icon_obj_2ar_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_2ar_neutral_locked.vtf"	"file"
	
	"materials\sprites\obj_icons\icon_obj_3l_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_3l_neutral_locked.vtf"	"file"

	
	"materials\sprites\obj_icons\icon_obj_4sw_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_4sw_neutral_locked.vtf"	"file"
	
	"materials\sprites\obj_icons\icon_obj_5f_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_5f_neutral_locked.vtf"	"file"

	"materials\sprites\obj_icons\icon_obj_6ba_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_6ba_neutral_locked.vtf"	"file"

	
	"materials\sprites\obj_icons\icon_obj_7bo_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_7bo_neutral_locked.vtf"	"file"

	"materials\sprites\obj_icons\icon_obj_8rw_blu.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_blu_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_red.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_red_locked.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_neutral.vtf"	"file"
	"materials\sprites\obj_icons\icon_obj_8rw_neutral_locked.vtf"	"file"

}